### ISSUE TITLE
Fix: Clean up NuGet package

### ISSUE THREAD

**Issue by seangwright** [Kentico/xperience-by-kentico-tag-manager#14]
### Brief bug description

The current NuGet package includes multiple copies of javascript IDE configuration files

### Repro steps

See <https://nuget.info/packages/Kentico.Xperience.TagManager/2.0.0>

### Expected behavior

The package only contains files that are needed for it to function correctly

### Test environment

 - Version 2.0.0

### Screenshots

![image](https://github.com/Kentico/xperience-by-kentico-tag-manager/assets/1382768/755cb51a-490d-41a6-aa4c-7fd54156fb6c)

**Comment by liparova** [comment]
Thank you for bringing this to our attention. We will investigate and keep you informed of our progress.

**Comment by bkapustik** [comment]
Hello, this is intentional. The package contains admin UI React component and a script which is called in the live site

**Comment by seangwright** [comment]
Correct, but it doesn't need `.eslintrc.json`, ect...
