### ISSUE TITLE
Tags should be able to opt-out of rendering in Page Builder / Preview

### ISSUE THREAD

**Issue by seangwright** [Kentico/xperience-by-kentico-tag-manager#20]
**Describe the bug**
Currently, GTM tags (and all other tags) are rendered when a web page is viewed in the Page Builder or Preview in Xperience.

This has the following effects

1. Tags that are meant for customers-only (ex: GTM/GA4/Clarity) are executed as marketers customize and preview a page
2. Pages that record the URL (ex: GA4) will capture administration-only URLs (ex: `/cmsctx/pm/...`)
3. Tags that expect all areas of the page to be "ready" when the tag loads will not work correctly because the Page Builder loads components asynchronously

**To Reproduce**
1. Add a GTM/GA4 tag to a website channel
2. View that site in the Page Builder/Preview
3. See that the GTM/GA4 tag is executing

**Expected behavior**
Sometimes the tag does something that is expected to always happen, even in the Page Builder, but other times (as explained above) it isn't correct.

Marketers should be able to opt-out of a tag rendering in either Page Builder, Preview, or both.
GA4 and GTM tags (and probably most others) should default to not rendering in the Page Builder or Preview.

**Screenshots**
Testing GA4 with the Tag Manager integration results in GA4 reports like this
![image](https://github.com/Kentico/xperience-by-kentico-tag-manager/assets/1382768/974fea71-c63d-4652-a23d-61627d68f302)

**Library Version**
2.0.1

**Comment by liparova** [comment]
Thank you for bringing this to our attention. We will investigate and keep you informed of our progress.

**Comment by michalJakubis** [comment]
Hello @seangwright, your feature request has been released in [v3.1.0](https://github.com/Kentico/xperience-by-kentico-tag-manager/releases/tag/v3.1.0).
