### ISSUE TITLE
ktc-tagmanager.js does not load in v3.0.0 - NuGet is missing staticwebassets folder

### ISSUE THREAD

**Issue by seangwright** [Kentico/xperience-by-kentico-tag-manager#23]
**Describe the bug**
The `ktc-tagmanager.js` script does not load in an ASPNET Core app using the NuGet package because the package is missing the `staticwebassets` folder in v3.0.0

Compare [v3.0.0](https://nuget.info/packages/Kentico.Xperience.TagManager/3.0.0) with [v2.0.0](https://nuget.info/packages/Kentico.Xperience.TagManager/2.0.0).

To correctly serve files from the [_content/My.Package/ path](https://github.com/Kentico/xperience-by-kentico-tag-manager/blob/v3.0.0/src/Kentico.Xperience.TagManager/Rendering/CodeSnippetTagHelperComponent.cs#L96) in an ASP.NET Core app requires assets be located in a `staticwebassets` folder in the root of the NuGet package.

**To Reproduce**
1. Add the v3.0.0 package to a Dancing Goat app
2. Follow the steps in the `README.md` to integrate it
3. Add a tag
4. Load the Dancing Goat home page
5. See that `ktc-tagmanager.js` fails to load, even though the tags render correctly

**Expected behavior**
The helper library loads correctly and is correctly configured in the NuGet package

**Library Version**
v3.0.0

**Comment by rubenschild** [comment]
Hello,

We are in the process of implementing Kentico Tag Manager for our Xperience website. However, we are encountering a 404 error indicating that the `ktc-tagmanager.js` script is not found.

Our current setup includes Tag Manager version 3.0.0 and Xperience version 29.0.2. Considering that this issue has been marked as closed alongside its corresponding pull request, can we expect the release of a new version, perhaps 3.0.1? Alternatively, should version 3.0.0 be functioning as expected from now on?

To reproduce; follow the mentioned steps in the issue above.

Kind regards, 
Ruben

**Comment by AmoretWakefly** [comment]
Hello,

I just installed Kentico Tag Manager v3.0.0 on our version 29.1.4 website and we are seeing the 404 error for this script. 
Are there any specific steps needed to get the package to update to fix this? 

Regards,
Angel

**Comment by AmoretWakefly** [comment]
Hello,

I just upgraded the NuGet package to 3.1.0, however, this issue still persists.

We get a 404 error stating that the Javascript file can't be found under the path: _/_content/Kentico.Xperience.TagManager/js/ktc-tagmanager.js_ 

Regards,
Angel
