### ISSUE TITLE
Add enabled field

### ISSUE THREAD

**Issue by roeldeb** [Kentico/xperience-by-kentico-tag-manager#28]
**Is your feature request related to a problem? Please describe.**
It would be helpfull if added tags could be enabled/disabled. When you would like to try without a certain script, you have to delete and add the entry again.

**Describe the solution you'd like**
Please add an Enabled field, to opt out certain scripts. Add enabled flag to overview page

**Comment by liparova** [comment]
Hi! Thanks for sharing your problem and a solution! We'll take a look at it soon and consider adding it to the original integration.

**Comment by bkapustik** [comment]
Hi, we have added the request feature.
Changes can be seen in the pull request https://github.com/Kentico/xperience-by-kentico-tag-manager/pull/32
You can use this feature in the Kentico.Xperience.TagManager NuGet v3.2.0
