### ISSUE TITLE
CI/CD related documentation suggestion

### ISSUE THREAD

**Issue by Lahvac** [Kentico/xperience-by-kentico-tag-manager#31]
**Is your feature request related to a problem? Please describe.**
We experienced following situation on our project which uses the Continuous Deployment feature and tag manager:

- the tag manager was successfully deployed on production environment
- we configured some tracking scripts on production environment
- after next production deployment done by CI/CD pipeline all tracking scripts were lost

The issue was caused by the CD restore. We fixed it by ignoring **kenticotagmanager.channelcodesnippet** and **kenticotagmanager.channelcodesnippetitem** in CD **repository.config** file.

Because there are usually some differences between production a dev site tag manager configurations this situation could happen to other developers.

**Describe the solution you'd like**
Add a friendly warning to the readme.md, which tells developers to consider excluding the kenticotagmanager objects in CD repository.config.

**Comment by liparova** [comment]
Hi! Thanks for sharing your problem and a solution! We'll take a look at it soon and consider adding it to the original integration.

**Comment by bkapustik** [comment]
The suggestion has been added in the following pr: https://github.com/Kentico/xperience-by-kentico-tag-manager/pull/36
