### ISSUE TITLE
Feature: Native support for Plausible and Fathom analytics

### ISSUE THREAD

**Issue by seangwright** [Kentico/xperience-by-kentico-tag-manager#39]
**Is your feature request related to a problem? Please describe.**
While many marketers use Google Analytics or Google Tag Manager to deliver tags for other providers to websites, some opt for more performant and less privacy invasive solutions like [Plausible](https://plausible.io) and [Fathom](https://usefathom.com).

**Describe the solution you'd like**
It would be great if the Tag Manager included pre-defined templates for both of these services.

**Describe alternatives you've considered**
We can use the custom HTML tags or add them with Google Tag Manager, but both have either a marketer usability or customer experience impact.

**Additional context**
n/a

**Comment by liparova** [comment]
Hi, I ust want to check if you are planning to include any other analytics tools like Matomo, or if we will only work with Plausible and Fathom. Should we focus only on these two, or do you want us to include more tools? 
Thanks!

**Comment by seangwright** [comment]
Fathom is a more premium product and Plausible/Matomo both have self-hosting/free options. Fathom + Matomo seems like the best options to add since Fathom is premium but Matomo has more features than Plausible and would appeal to Kentico's customers more.

**Comment by Sapphirress** [comment]
Hi Sean, our PM decided that this is not a priority for us at the moment and will not put it on the roadmap. He will discuss with you directly if needed.
