### ISSUE TITLE
Code name field does not indicate error

### ISSUE THREAD

**Issue by jeroenfurst** [Kentico/xperience-by-kentico-tag-manager#8]
### Brief bug description

We tried to save a new code snippet with a code name containing spaces. After submission you get an error message but no indication what went wrong. Even nothing is displayed in the event log, allthough the global error message in the bottom references it.

### Repro steps

1. Go to 'Code snippets'
2. Create a new snippet
3. Fill in code name containing spaces e.g. "Google Tag Manager"
4. Fill/Select the other fields and click save
5. Notice the error message

### Expected behavior

We would expect that the code name field would indicate that it doesn't allow spaces and/or we would expect a message in the event log.

### Test environment

 - Platform/OS: [.NET 8, Azure]
 - Browser [Firefox]
 - Version [28.3.2]

### Additional context

NA

### Screenshots

NA

**Comment by bkapustik** [comment]
Hello the fixed is included in the release 2.0.0
